package seeder

import "log"

// TeamRating holds attack and defense strength (1-100).
// Based on 2024-25 season standings + manual overrides for elite clubs.
type TeamRating struct {
	Attack  int
	Defense int
}

// leagueDefaults — mid-table fallback when a team is not in the ratings table.
var leagueDefaults = map[string]TeamRating{
	"eng.1": {Attack: 75, Defense: 73},
	"esp.1": {Attack: 76, Defense: 73},
	"ger.1": {Attack: 75, Defense: 72},
	"ita.1": {Attack: 74, Defense: 71},
	"fra.1": {Attack: 73, Defense: 70},
	"tur.1": {Attack: 68, Defense: 66},
	"ned.1": {Attack: 68, Defense: 66},
	"por.1": {Attack: 67, Defense: 65},
	"eng.2": {Attack: 63, Defense: 61},
	"sco.1": {Attack: 63, Defense: 61},
}

// teamRatings — real-world strength for every team ESPN exposes across supported leagues.
var teamRatings = map[string]TeamRating{
	"1. FC Heidenheim 1846": {Attack: 59, Defense: 54},
	"1. FC Union Berlin": {Attack: 63, Defense: 64},
	"AC Milan": {Attack: 82, Defense: 80},
	"AFC Bournemouth": {Attack: 78, Defense: 72},
	"AJ Auxerre": {Attack: 62, Defense: 71},
	"AS Monaco": {Attack: 80, Defense: 74},
	"AS Roma": {Attack: 76, Defense: 76},
	"AVS": {Attack: 50, Defense: 48},
	"AZ Alkmaar": {Attack: 74, Defense: 72},
	"Aberdeen": {Attack: 54, Defense: 58},
	"Ajax Amsterdam": {Attack: 80, Defense: 70},
	"Alanyaspor": {Attack: 58, Defense: 64},
	"Alavés": {Attack: 66, Defense: 62},
	"Alverca": {Attack: 56, Defense: 57},
	"Angers": {Attack: 60, Defense: 70},
	"Antalyaspor": {Attack: 53, Defense: 53},
	"Arouca": {Attack: 61, Defense: 53},
	"Arsenal": {Attack: 90, Defense: 92},
	"Aston Villa": {Attack: 78, Defense: 76},
	"Atalanta": {Attack: 82, Defense: 74},
	"Athletic Club": {Attack: 67, Defense: 61},
	"Atlético Madrid": {Attack: 78, Defense: 90},
	"Barcelona": {Attack: 94, Defense: 82},
	"Bayer Leverkusen": {Attack: 88, Defense: 84},
	"Bayern Munich": {Attack: 93, Defense: 82},
	"Benfica": {Attack: 82, Defense: 80},
	"Besiktas": {Attack: 78, Defense: 74},
	"Birmingham City": {Attack: 63, Defense: 67},
	"Blackburn Rovers": {Attack: 58, Defense: 65},
	"Bologna": {Attack: 72, Defense: 74},
	"Borussia Dortmund": {Attack: 86, Defense: 78},
	"Borussia Mönchengladbach": {Attack: 62, Defense: 67},
	"Braga": {Attack: 72, Defense: 74},
	"Brentford": {Attack: 76, Defense: 72},
	"Brest": {Attack: 67, Defense: 67},
	"Brighton & Hove Albion": {Attack: 74, Defense: 72},
	"Bristol City": {Attack: 64, Defense: 66},
	"Burnley": {Attack: 62, Defense: 56},
	"C.D. Nacional": {Attack: 55, Defense: 59},
	"Cagliari": {Attack: 66, Defense: 68},
	"Casa Pia": {Attack: 53, Defense: 54},
	"Caykur Rizespor": {Attack: 61, Defense: 57},
	"Celta Vigo": {Attack: 72, Defense: 71},
	"Celtic": {Attack: 78, Defense: 72},
	"Charlton Athletic": {Attack: 59, Defense: 65},
	"Chelsea": {Attack: 82, Defense: 78},
	"Como": {Attack: 80, Defense: 85},
	"Coventry City": {Attack: 78, Defense: 76},
	"Cremonese": {Attack: 62, Defense: 64},
	"Crystal Palace": {Attack: 69, Defense: 71},
	"Derby County": {Attack: 67, Defense: 66},
	"Dundee": {Attack: 56, Defense: 56},
	"Dundee United": {Attack: 59, Defense: 56},
	"Eintracht Frankfurt": {Attack: 76, Defense: 72},
	"Elche": {Attack: 68, Defense: 61},
	"Espanyol": {Attack: 67, Defense: 63},
	"Estoril": {Attack: 62, Defense: 55},
	"Estrela": {Attack: 55, Defense: 54},
	"Everton": {Attack: 72, Defense: 72},
	"Excelsior": {Attack: 58, Defense: 66},
	"Eyupspor": {Attack: 53, Defense: 58},
	"FC Augsburg": {Attack: 64, Defense: 64},
	"FC Cologne": {Attack: 62, Defense: 60},
	"FC Famalicao": {Attack: 62, Defense: 70},
	"FC Groningen": {Attack: 62, Defense: 73},
	"FC Porto": {Attack: 80, Defense: 84},
	"FC Twente": {Attack: 67, Defense: 77},
	"FC Utrecht": {Attack: 65, Defense: 76},
	"FC Volendam": {Attack: 55, Defense: 66},
	"Falkirk": {Attack: 61, Defense: 57},
	"Fatih Karagümrük": {Attack: 52, Defense: 53},
	"Fenerbahce": {Attack: 83, Defense: 77},
	"Feyenoord Rotterdam": {Attack: 82, Defense: 74},
	"Fiorentina": {Attack: 67, Defense: 69},
	"Fortuna Sittard": {Attack: 60, Defense: 63},
	"Fulham": {Attack: 73, Defense: 73},
	"Galatasaray": {Attack: 84, Defense: 78},
	"Gaziantep FK": {Attack: 58, Defense: 52},
	"Genclerbirligi": {Attack: 55, Defense: 59},
	"Genoa": {Attack: 66, Defense: 69},
	"Getafe": {Attack: 65, Defense: 79},
	"Gil Vicente": {Attack: 62, Defense: 66},
	"Girona": {Attack: 65, Defense: 62},
	"Go Ahead Eagles": {Attack: 62, Defense: 67},
	"Goztepe": {Attack: 66, Defense: 64},
	"Hamburg SV": {Attack: 62, Defense: 67},
	"Heart of Midlothian": {Attack: 68, Defense: 70},
	"Heerenveen": {Attack: 65, Defense: 70},
	"Hellas Verona": {Attack: 57, Defense: 59},
	"Heracles Almelo": {Attack: 52, Defense: 50},
	"Hibernian": {Attack: 66, Defense: 67},
	"Hull City": {Attack: 68, Defense: 64},
	"Internazionale": {Attack: 86, Defense: 88},
	"Ipswich Town": {Attack: 68, Defense: 62},
	"Istanbul Basaksehir": {Attack: 70, Defense: 70},
	"Juventus": {Attack: 78, Defense: 86},
	"Kasimpasa": {Attack: 54, Defense: 58},
	"Kayserispor": {Attack: 50, Defense: 48},
	"Kilmarnock": {Attack: 59, Defense: 52},
	"Kocaelispor": {Attack: 52, Defense: 66},
	"Konyaspor": {Attack: 60, Defense: 59},
	"Lazio": {Attack: 74, Defense: 72},
	"Le Havre AC": {Attack: 61, Defense: 71},
	"Lecce": {Attack: 62, Defense: 68},
	"Leeds United": {Attack: 72, Defense: 66},
	"Leicester City": {Attack: 74, Defense: 68},
	"Lens": {Attack: 74, Defense: 72},
	"Levante": {Attack: 67, Defense: 57},
	"Lille": {Attack: 72, Defense: 78},
	"Liverpool": {Attack: 91, Defense: 85},
	"Livingston": {Attack: 49, Defense: 44},
	"Lorient": {Attack: 70, Defense: 71},
	"Lyon": {Attack: 76, Defense: 70},
	"Mainz": {Attack: 63, Defense: 68},
	"Mallorca": {Attack: 67, Defense: 61},
	"Manchester City": {Attack: 94, Defense: 88},
	"Manchester United": {Attack: 80, Defense: 76},
	"Marseille": {Attack: 78, Defense: 72},
	"Metz": {Attack: 57, Defense: 53},
	"Middlesbrough": {Attack: 69, Defense: 73},
	"Millwall": {Attack: 67, Defense: 72},
	"Moreirense": {Attack: 57, Defense: 59},
	"Motherwell": {Attack: 67, Defense: 72},
	"NAC Breda": {Attack: 54, Defense: 64},
	"NEC Nijmegen": {Attack: 72, Defense: 71},
	"Nantes": {Attack: 57, Defense: 64},
	"Napoli": {Attack: 84, Defense: 78},
	"Newcastle United": {Attack: 78, Defense: 80},
	"Nice": {Attack: 63, Defense: 63},
	"Norwich City": {Attack: 65, Defense: 67},
	"Nottingham Forest": {Attack: 71, Defense: 71},
	"Osasuna": {Attack: 66, Defense: 66},
	"Oxford United": {Attack: 58, Defense: 64},
	"PEC Zwolle": {Attack: 58, Defense: 59},
	"PSV Eindhoven": {Attack: 86, Defense: 72},
	"Paris FC": {Attack: 70, Defense: 70},
	"Paris Saint-Germain": {Attack: 92, Defense: 80},
	"Parma": {Attack: 63, Defense: 72},
	"Pisa": {Attack: 57, Defense: 54},
	"Portsmouth": {Attack: 60, Defense: 63},
	"Preston North End": {Attack: 62, Defense: 64},
	"Queens Park Rangers": {Attack: 63, Defense: 59},
	"RB Leipzig": {Attack: 82, Defense: 76},
	"Rangers": {Attack: 76, Defense: 74},
	"Rayo Vallecano": {Attack: 67, Defense: 74},
	"Real Betis": {Attack: 75, Defense: 72},
	"Real Madrid": {Attack: 93, Defense: 88},
	"Real Oviedo": {Attack: 58, Defense: 55},
	"Real Sociedad": {Attack: 72, Defense: 76},
	"Rio Ave": {Attack: 55, Defense: 55},
	"SC Freiburg": {Attack: 67, Defense: 67},
	"Samsunspor": {Attack: 68, Defense: 66},
	"Santa Clara": {Attack: 55, Defense: 62},
	"Sassuolo": {Attack: 69, Defense: 71},
	"Sevilla": {Attack: 67, Defense: 58},
	"Sheffield United": {Attack: 66, Defense: 62},
	"Sheffield Wednesday": {Attack: 48, Defense: 46},
	"Southampton": {Attack: 70, Defense: 64},
	"Sparta Rotterdam": {Attack: 58, Defense: 65},
	"Sporting CP": {Attack: 84, Defense: 82},
	"St Mirren": {Attack: 49, Defense: 57},
	"St. Pauli": {Attack: 57, Defense: 60},
	"Stade Rennais": {Attack: 79, Defense: 74},
	"Stoke City": {Attack: 61, Defense: 66},
	"Strasbourg": {Attack: 77, Defense: 74},
	"Sunderland": {Attack: 71, Defense: 74},
	"Swansea City": {Attack: 63, Defense: 66},
	"TSG Hoffenheim": {Attack: 73, Defense: 73},
	"Telstar": {Attack: 59, Defense: 66},
	"Tondela": {Attack: 51, Defense: 54},
	"Torino": {Attack: 68, Defense: 63},
	"Tottenham Hotspur": {Attack: 84, Defense: 74},
	"Toulouse": {Attack: 71, Defense: 72},
	"Trabzonspor": {Attack: 76, Defense: 72},
	"Udinese": {Attack: 70, Defense: 71},
	"Valencia": {Attack: 68, Defense: 64},
	"VfB Stuttgart": {Attack: 75, Defense: 75},
	"VfL Wolfsburg": {Attack: 61, Defense: 56},
	"Villarreal": {Attack: 80, Defense: 74},
	"Vitória de Guimaraes": {Attack: 58, Defense: 59},
	"Watford": {Attack: 62, Defense: 62},
	"Werder Bremen": {Attack: 60, Defense: 61},
	"West Bromwich Albion": {Attack: 59, Defense: 65},
	"West Ham United": {Attack: 69, Defense: 64},
	"Wolverhampton Wanderers": {Attack: 58, Defense: 59},
	"Wrexham": {Attack: 67, Defense: 64},
}

// addedRatings stores ratings for teams discovered at import time.
var addedRatings = map[string]TeamRating{}

// LookupTeamRating returns the rating for a team by ESPN display name.
// Unknown teams get a league-average rating and are added to addedRatings.
func LookupTeamRating(name, leagueCode string) TeamRating {
	if r, ok := teamRatings[name]; ok {
		return r
	}
	if r, ok := addedRatings[name]; ok {
		return r
	}
	def, ok := leagueDefaults[leagueCode]
	if !ok {
		def = TeamRating{Attack: 65, Defense: 65}
	}
	addedRatings[name] = def
	log.Printf("Added default rating for new team %s (%s): ATK=%d DEF=%d", name, leagueCode, def.Attack, def.Defense)
	return def
}
